# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 345)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(80, 50, 311, 41))
        self.progressBar.setToolTipDuration(-1)
        self.progressBar.setMaximum(1)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(80, 90, 41, 141))
        self.progressBar_2.setMaximum(1)
        self.progressBar_2.setProperty("value", -1)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(320, 90, 41, 141))
        self.progressBar_3.setMaximum(1)
        self.progressBar_3.setProperty("value", -1)
        self.progressBar_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_3.setInvertedAppearance(True)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_4.setGeometry(QtCore.QRect(80, 230, 311, 41))
        self.progressBar_4.setMaximum(1)
        self.progressBar_4.setProperty("value", -1)
        self.progressBar_4.setInvertedAppearance(True)
        self.progressBar_4.setObjectName("progressBar_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 290, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.timer = QtCore.QBasicTimer()
        self.pushButton.clicked.connect(self.run)

    def run(self):
        if self.timer.isActive():
            self.timer.stop()
            self.pushButton.setText('开始')
            self.progressBar.setMaximum(1)
            self.progressBar_2.setMaximum(1)
            self.progressBar_3.setMaximum(1)
            self.progressBar_4.setMaximum(1)
        else:
            self.timer.start(100, MainWindow)
            self.pushButton.setText('停止')
            self.progressBar.setMaximum(0)
            self.progressBar_2.setMaximum(0)
            self.progressBar_3.setMaximum(0)
            self.progressBar_4.setMaximum(0)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "跑马灯效果"))
        self.pushButton.setText(_translate("MainWindow", "开始"))


# 主方法，程序从此处启动PyQt设计的窗体
if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # app.setStyle("Fusion")

    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())
