# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tree.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 325)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.setAlternatingRowColors(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.treeWidget.clicked.connect(self.gettreetext)

    def gettreetext(self, index):
        item = self.treeWidget.currentItem()
        QtWidgets.QMessageBox.information(MainWindow, '提示', '您选择的是：%s -- %s' %(item.text(0), item.text(1)), QtWidgets.QMessageBox.Ok)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "姓名"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "职务"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "组织结构"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "任正非"))
        self.treeWidget.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "华为董事长"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "马云"))
        self.treeWidget.topLevelItem(0).child(1).setText(1, _translate("MainWindow", "阿里巴巴董事长"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "马化腾"))
        self.treeWidget.topLevelItem(0).child(2).setText(1, _translate("MainWindow", "腾讯CEO"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "李彦宏"))
        self.treeWidget.topLevelItem(0).child(3).setText(1, _translate("MainWindow", "百度CEO"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "董明珠"))
        self.treeWidget.topLevelItem(0).child(4).setText(1, _translate("MainWindow", "格力董事长"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    # app.setStyle("Fusion")

    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())
