# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(398, 224)
        LoginWindow.setMinimumSize(QtCore.QSize(398, 224))
        LoginWindow.setMaximumSize(QtCore.QSize(398, 224))
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 0, 398, 89))
        self.image.setMinimumSize(QtCore.QSize(398, 89))
        self.image.setMaximumSize(QtCore.QSize(398, 89))
        self.image.setStyleSheet("border-image: url(:/r/1.png);")
        self.image.setText("")
        self.image.setObjectName("image")
        self.lable_username = QtWidgets.QLabel(self.centralwidget)
        self.lable_username.setGeometry(QtCore.QRect(110, 120, 54, 12))
        self.lable_username.setObjectName("lable_username")
        self.lable_password = QtWidgets.QLabel(self.centralwidget)
        self.lable_password.setGeometry(QtCore.QRect(110, 150, 54, 12))
        self.lable_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lable_password.setObjectName("lable_password")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 190, 61, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.login)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 190, 61, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(LoginWindow.close)

        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(170, 120, 131, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(170, 150, 131, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "系统登录"))
        self.lable_username.setText(_translate("LoginWindow", "用户名："))
        self.lable_password.setText(_translate("LoginWindow", "密   码："))
        self.pushButton.setText(_translate("LoginWindow", "登录"))
        self.pushButton_2.setText(_translate("LoginWindow", "退出"))

    def login(self):
        from PyQt5.QtWidgets import QMessageBox
        if self.username.text() != "" and self.password.text() != '':
            QMessageBox.information(None, "消息", "登录成功", QMessageBox.Yes)
        else:
            QMessageBox.information(None, "消息", "用户名或密码不能为空", QMessageBox.Yes)

import r1_rc
