CREATE DATABASE SPJ;

USE SPJ;

CREATE TABLE S (
	SNO CHAR ( 9 ) PRIMARY KEY,
	SNAME CHAR ( 10 ) ,
	STATUS INT,
	CITY CHAR ( 10 ) ,
	CONSTRAINT C1 CHECK (STATUS BETWEEN 10 AND 30),
	CONSTRAINT C2 UNIQUE (SNAME)
 );

CREATE TABLE P (
	PNO CHAR ( 9 ) PRIMARY KEY,
	PNAME CHAR ( 10 ),
	COLOR CHAR ( 10 ),
	WEIGHT INT,
	CONSTRAINT C3 CHECK (COLOR IN ('红', '绿', '蓝', '黄', '青', '黑', '紫', '白'))
);

CREATE TABLE J (
	JNO CHAR ( 9 ) PRIMARY KEY,
	JNAME CHAR ( 10 ),
	CITY CHAR ( 10 )
);

CREATE TABLE SPJ (
	SNO CHAR ( 9 ),
	PNO CHAR ( 9 ),
	JNO CHAR ( 9 ),
	QTY INT,
	PRIMARY KEY ( SNO, PNO, JNO ),
	FOREIGN KEY ( SNO ) REFERENCES S ( SNO ),
	FOREIGN KEY ( PNO ) REFERENCES P ( PNO ),
	FOREIGN KEY ( JNO ) REFERENCES J ( JNO ),
	CONSTRAINT C4 CHECK (QTY BETWEEN 1 AND 1000)
);

INSERT INTO S (SNO, SNAME, STATUS, CITY)
VALUES ('S1','精益',20,'天津'),
			 ('S2','精益',10,'北京');


INSERT INTO P(PNO,PNAME,COLOR,WEIGHT)
VALUES ('P1','螺母','橙',12);

ALTER TABLE SPJ
 DROP  CONSTRAINT C4;

ALTER TABLE S
 DROP  CONSTRAINT C2;



















